let data = [
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "manager",
    department: "HR",
    salary: 100,
    id: 1,
  },
  {
    name: "Harsh Gajera",
    email: "harsh@gmail.com",
    gender: "male",
    roll: "people function",
    department: "HR",
    salary: 155,
    id: 2,
  },
  {
    name: "Deepa",
    email: "Deeepa@gmail.com",
    gender: "female",
    roll: "Account",
    department: "Marketing",
    salary: 205,
    id: 3,
  },
  {
    name: "allie Smith",
    email: "johnsmith@gmail.com",
    gender: "female",
    roll: "Saleswoman",
    department: "Marketing",
    salary: 85,
    id: 4,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "engineer",
    department: "IT",
    salary: 70,
    id: 5,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "Tester",
    department: "IT",
    salary: 96,
    id: 6,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "Cashier",
    department: "Finance",
    salary: 101,
    id: 7,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "Just employee",
    department: "Finance",
    salary: 47,
    id: 8,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "manager",
    department: "HR",
    salary: 1042,
    id: 9,
  },
  {
    name: "Harsh Gajera",
    email: "harsh@gmail.com",
    gender: "male",
    roll: "people function",
    department: "HR",
    salary: 55,
    id: 10,
  },
  {
    name: "Deepa",
    email: "Deeepa@gmail.com",
    gender: "female",
    roll: "Account",
    department: "Marketing",
    salary: 2105,
    id: 11,
  },
  {
    name: "allie Smith",
    email: "johnsmith@gmail.com",
    gender: "female",
    roll: "Saleswoman",
    department: "Marketing",
    salary: 845,
    id: 12,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "engineer",
    department: "IT",
    salary: 700,
    id: 13,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "Tester",
    department: "IT",
    salary: 945,
    id: 14,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "Cashier",
    department: "Finance",
    salary: 1059,
    id: 15,
  },
  {
    name: "John Smith",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "Just employee",
    department: "Finance",
    salary: 860,
    id: 16,
  },
  {
    name: "John Smith Hahhh",
    email: "johnsmith@gmail.com",
    gender: "male",
    roll: "engineer",
    department: "IT",
    salary: 700,
    id: 17,
  },
  {
    name: "Virat Kohli",
    email: "india@india.com",
    gender: "male",
    roll: "Marketing",
    department: "Finance",
    salary: 0,
    id: 18,
  },
  {
    name: "Rohit",
    email: "india@india.com",
    gender: "male",
    roll: "Marketing",
    department: "Finance",
    salary: 100,
    id: 19,
  },
  {
    name: "Atif Aslam",
    email: "india@india.com",
    gender: "male",
    roll: "Marketing",
    department: "IT",
    salary: 3000,
    id: 20,
  },
  {
    name: "Harsu",
    email: "harsh.gajera163@gmail.com",
    gender: "male",
    roll: "Engineer",
    department: "Marketing",
    salary: 1564274,
    id: 21,
  },
  {
    name: "Harsu",
    email: "harsh.gajera163@gmail.com",
    gender: "male",
    roll: "Engineer",
    department: "HR",
    salary: 1,
    id: 22,
  },
  {
    name: "Harsh Gajera",
    email: "harsh.gajera@mindtree.com",
    gender: "male",
    roll: "Engineer",
    department: "HR",
    salary: 1564274,
    id: 23,
  },
  {
    name: "Harsh XYZ",
    email: "harsh@mindtree.com",
    gender: "male",
    roll: "Engineer",
    department: "Marketing",
    salary: 1564274,
    id: 24,
  },
  {
    name: "Harsh",
    email: "harsh@gajera.com",
    gender: "male",
    roll: "Engineer",
    department: "IT",
    salary: 15674,
    id: 25,
  },
];

export { data };
